name: Broken Link Report
description: File a broken link report
title: "Broken Link:"
labels: ["bug"]
projects: ["ros-infrastructure/rosindex"]
body:

  - type: input
    id: 404page
    attributes:
      label: 404 Page URL
      description: Enter the url of the page that doesn't exist
      placeholder: Failed to automatically detect 404 page. Please enter url here.
    validations:
      required: true

  - type: input
    id: referer
    attributes:
      label: Referrer URL
      description: Enter the URL of the referring page which has the wrong link.
      placeholder: Automatic detection of the referrer page failed, please enter it here.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Please describe where the link is that you followed if it might not be obvious on the referring page. If any additional information is needed, please provide it here too.
    validations:
      required: false